[package]
name = "entity-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
n0-future = "0.1.3"
tokio = { version = "1.46.0", features = ["full"] }
tracing = "0.1.41"

[dev-dependencies]
hex = "0.4.3"
tempfile = "3.20.0"
testresult = "0.4.1"
atomic_refcell = "0.1.13"